name: two_jobs

on: push

jobs:
  job1:
    name: First job
    runs-on: ubuntu-latest
    steps:
      - name: Step two
        run: env | sort
  job2:
    name: Second job (with dependency)
    needs: job1
    runs-on: windows-latest
    steps:
      - name: Step two
        run: "Get-ChildItem Env: | Sort-Object Name"

